import {
  ConflictException,
  Injectable,
  NotFoundException,
  UnprocessableEntityException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { Organisation } from '../organisations/entities/organisation.entity.js';

import {
  IlrReturnFileDto,
  IlrReturnFileQueryDto,
} from './dto/ilr-return-file.dto.js';
import { IlrLearnerRecord } from './entities/ilr-learner-record.entity.js';
import { IlrLearnerRecordStatus } from './enums/ilr-learner-record-status.enum.js';
import {
  IlrPayloadSerializerService,
  ilrReturnFilename,
} from './ilr-payload-serializer.service.js';

import type { AuthenticatedUser } from '../auth/interfaces/authenticated-user.interface.js';

/**
 * What the file covers, stated on screen and inside the file. The mapping
 * config is the v1 apprenticeship subset (docs/ilr.md, "v1 limitations"),
 * so Submit Learner Data may reject a file that is complete by our records
 * and incomplete by ESFA's schema. That is said, not discovered at upload.
 */
export const ILR_RETURN_FILE_COVERAGE =
  'Generated by Gradlly from the v1 ILR field mapping: an apprenticeship ' +
  'subset of the ESFA ILR specification, not the full annual schema. ESFA ' +
  'Submit Learner Data may reject this file until the field mapping is ' +
  'complete. Every learner record in the collection period is included.';

/**
 * 5.4 — the provider's whole ILR return as one XML file.
 *
 * F2.3.2 and §8.2 specify direct submission to ESFA's API; this is the file
 * a provider uploads to Submit Learner Data instead, built from the same
 * learner records and serializer as the submit path.
 *
 * ── A PARTIAL RETURN IS REFUSED, NOT PRODUCED ───────────────────────────────
 *
 * The file is every learner record in the collection period, or nothing. If
 * any record has not passed validation the request is refused with the
 * count, rather than silently leaving those learners out — a return missing
 * learners is a funding claim that is short, and an upload that ESFA accepts
 * would not say so. The same holds for a period with no records at all
 * (404, not an empty file) and for a provider with no UKPRN (the file is
 * named and headed by it).
 */
@Injectable()
export class IlrReturnFileService {
  constructor(
    @InjectRepository(IlrLearnerRecord)
    private readonly recordRepo: Repository<IlrLearnerRecord>,
    @InjectRepository(Organisation)
    private readonly organisationRepo: Repository<Organisation>,
    private readonly serializer: IlrPayloadSerializerService,
  ) {}

  async build(
    user: AuthenticatedUser,
    query: IlrReturnFileQueryDto,
  ): Promise<IlrReturnFileDto> {
    const organisationId = user.organisationId!;
    const { collectionPeriod } = query;

    const organisation = await this.organisationRepo.findOne({
      where: { id: organisationId },
      select: ['id', 'ukprn'],
    });
    const ukprn = organisation?.ukprn?.trim();
    if (!ukprn) {
      throw new UnprocessableEntityException(
        'Your organisation has no UKPRN. An ILR file is named and headed by it; add it to the organisation before downloading.',
      );
    }

    const records = await this.recordRepo.find({
      where: { organisationId, collectionPeriod, isDeleted: false },
      order: { createdAt: 'ASC', id: 'ASC' },
    });
    if (records.length === 0) {
      throw new NotFoundException(
        `There are no ILR learner records for collection period ${collectionPeriod}. Build them before downloading the return.`,
      );
    }

    const academicYears = [...new Set(records.map((r) => r.academicYear))];
    if (academicYears.length > 1) {
      throw new ConflictException(
        `The learner records for ${collectionPeriod} span more than one academic year (${academicYears.join(', ')}). One ILR file covers one year; correct the records first.`,
      );
    }

    const notValidated = records.filter(
      (r) => r.status !== IlrLearnerRecordStatus.VALIDATED,
    );
    if (notValidated.length > 0) {
      const failed = notValidated.filter(
        (r) => r.status === IlrLearnerRecordStatus.VALIDATION_FAILED,
      ).length;
      const pending = notValidated.length - failed;
      throw new ConflictException(
        `${notValidated.length} of ${records.length} learner records for ${collectionPeriod} have not passed validation ` +
          `(${failed} failed, ${pending} not yet validated). A file without them would be an incomplete return, ` +
          'so none was produced. Validate them and download again.',
      );
    }

    const generatedAt = new Date();
    const academicYear = academicYears[0];
    const mappingConfigVersions = [
      ...new Set(records.map((r) => r.mappingConfigVersion)),
    ].sort((a, b) => a - b);

    const xml = this.serializer.toIlrReturnXml({
      ukprn,
      academicYear,
      collectionPeriod,
      generatedAt,
      mappingConfigVersions,
      coverage: ILR_RETURN_FILE_COVERAGE,
      learners: records.map((r) => ({
        learnerRecordId: r.id,
        fields: r.fields,
      })),
    });

    return {
      filename: ilrReturnFilename(ukprn, academicYear, generatedAt),
      ukprn,
      academicYear,
      collectionPeriod,
      learnerCount: records.length,
      mappingConfigVersions,
      generatedAt: generatedAt.toISOString(),
      coverage: ILR_RETURN_FILE_COVERAGE,
      xml,
    };
  }
}
