/* eslint-disable no-console */
/**
 * Creates a verified user + organisation for k6 smoke tests.
 * Writes load/k6/.env.local (gitignored).
 *
 * Usage: BASE_URL=http://localhost:3010 yarn load:setup
 */
import 'dotenv/config';

import { randomInt } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import Redis from 'ioredis';
import { Client } from 'pg';

const BASE_URL = (process.env.BASE_URL || 'http://localhost:3010').replace(
  /\/+$/,
  '',
);
const ENV_FILE = resolve(process.cwd(), 'load/k6/.env.local');

function buildOrgPayload(name: string) {
  const ukprn = String(
    (Date.now() + randomInt(0, 10_000)) % 100_000_000,
  ).padStart(8, '0');
  return {
    name,
    ukprn,
    address: '1 Load Test Lane',
    city: 'London',
    postcode: 'SW1A 1AA',
    country: 'United Kingdom',
    orgEmail: `load-${ukprn}@example.com`,
  };
}

async function jsonFetch(
  path: string,
  init: RequestInit = {},
): Promise<{ status: number; body: Record<string, unknown> }> {
  const res = await fetch(`${BASE_URL}${path}`, {
    ...init,
    headers: {
      'Content-Type': 'application/json',
      ...(init.headers as Record<string, string> | undefined),
    },
  });
  const body = (await res.json()) as Record<string, unknown>;
  return { status: res.status, body };
}

async function getUserIdByEmail(email: string): Promise<string> {
  const client = new Client({
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432', 10),
    user: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
  });
  await client.connect();
  try {
    const result = await client.query<{ id: string }>(
      'SELECT id FROM users WHERE email = $1 LIMIT 1',
      [email],
    );
    const id = result.rows[0]?.id;
    if (!id) {
      throw new Error(`User not found for email ${email}`);
    }
    return id;
  } finally {
    await client.end();
  }
}

async function findEmailVerificationToken(userId: string): Promise<string> {
  const redis = new Redis({
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT || '6379', 10),
    password: process.env.REDIS_PASSWORD || undefined,
  });
  try {
    const keys = await redis.keys('email-verify:*');
    for (const key of keys) {
      const value = await redis.get(key);
      if (value === userId) {
        return key.replace('email-verify:', '');
      }
    }
    throw new Error(`No verification token in Redis for user ${userId}`);
  } finally {
    await redis.quit();
  }
}

async function main(): Promise<void> {
  const email = `k6-smoke-${Date.now()}@example.com`;
  const password = 'K6-Smoke-P@ssw0rd!';

  console.log(`Provisioning k6 smoke user against ${BASE_URL} ...`);

  const signup = await jsonFetch('/api/v1/auth/signup', {
    method: 'POST',
    body: JSON.stringify({
      firstName: 'K6',
      lastName: 'Smoke',
      email,
      password,
    }),
  });
  if (signup.status !== 201) {
    throw new Error(
      `Signup failed (${signup.status}): ${JSON.stringify(signup.body)}`,
    );
  }

  const userId = await getUserIdByEmail(email);
  let token = await findEmailVerificationToken(userId);

  if (!token) {
    await jsonFetch('/api/v1/auth/resend-verification', {
      method: 'POST',
      body: JSON.stringify({ email }),
    });
    token = await findEmailVerificationToken(userId);
  }

  const verify = await jsonFetch('/api/v1/auth/verify-email', {
    method: 'POST',
    body: JSON.stringify({ token }),
  });
  if (verify.status !== 200) {
    throw new Error(
      `Verify email failed (${verify.status}): ${JSON.stringify(verify.body)}`,
    );
  }

  const accessToken = (verify.body.data as { accessToken: string }).accessToken;

  const org = await jsonFetch('/api/v1/organisations', {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}` },
    body: JSON.stringify(buildOrgPayload('K6 Smoke Org')),
  });
  if (org.status !== 201) {
    throw new Error(
      `Create organisation failed (${org.status}): ${JSON.stringify(org.body)}`,
    );
  }

  const orgId = (org.body.data as { id: string }).id;

  const envContents = `# Generated by scripts/provision-k6-smoke-user.ts — do not commit
BASE_URL=${BASE_URL}
TEST_EMAIL=${email}
TEST_PASSWORD=${password}
ORG_ID=${orgId}
`;

  writeFileSync(ENV_FILE, envContents, 'utf8');

  console.log(`Wrote ${ENV_FILE}`);
  console.log(`  TEST_EMAIL=${email}`);
  console.log(`  ORG_ID=${orgId}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
