import { randomInt } from 'node:crypto';

let ukprnSequence = 0;

/** Builds a valid POST /organisations body. Slug is generated by the API. */
export function buildOrgPayload(name: string, ukprn?: string) {
  ukprnSequence += 1;
  const resolvedUkprn =
    ukprn ??
    String(
      (Date.now() + ukprnSequence * 997 + randomInt(0, 10_000)) % 100_000_000,
    ).padStart(8, '0');

  return {
    name,
    ukprn: resolvedUkprn,
    address: '1 Test Lane',
    city: 'London',
    postcode: 'SW1A 1AA',
    country: 'United Kingdom',
    orgEmail: `info@${resolvedUkprn}.co.uk`,
  };
}
